The warning handles the case of having an except clause which handles as an exception
the result of a binary operation, as seen in the following example.


    try:
        ...
    except ZeroDivisionError or ValueError:
        pass

This could be written instead as:

    try:
        ...
    except (ZeroDivisionError, ValueError):
        pass
      